name = "aoc2024"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.52.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.6.1 and < 2.0.0"
